services:
  app:
    restart: always
    build: .
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn --timeout=30 --workers=4 --bind 0.0.0.0:8000 accounting_system.wsgi:application"
    volumes:
      - .:/code
      - static-volume:/code/collected_static
    ports:
      - "8000:8000"
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  static-volume:
